FROM dictybase/jbrowse:1.11.6
MAINTAINER Siddhartha Basu <siddhartha-basu@northwestern.edu>
RUN cd jbrowse && mkdir -p data && ln -sf /data/jbrowse data && ln -sf /config/jbrowse/jbrowse.conf jbrowse.conf
